### ISSUE TITLE
Socket.io 1.4.0 broke feathers

### ISSUE THREAD

**Issue by ekryski** [feathersjs/feathers-commons#10]
The call to `info.clients()` now returns an object. Bad versioning :cry:

See: https://github.com/feathersjs/feathers-commons/blob/master/src/sockets/helpers.js#L37

**Comment by ekryski** [comment]
Someone created an issue in socket.io already. https://github.com/socketio/socket.io/issues/2368

**Comment by daffl** [comment]
Sounds good. What does the object look like? Can we map it back to an array if necessary?

**Comment by ekryski** [comment]
It's just empty. We can map it or just fix our versioning to be `1.3.x` in this repo.

**Comment by ekryski** [comment]
Will need to be updated for the 2.0 release but I'd like to see what happens in the socket.io first. This just happened a few hours ago.

**Comment by ekryski** [comment]
This should be good all releases now. Even the Feathers 2.0 release, regardless of whether they revert that change in the socket.io lib.
