### ISSUE TITLE
babel inside package.json breaks react-native

### ISSUE THREAD

**Issue by ekryski** [feathersjs/feathers-commons#9]
We need to move the babel config to a `.babelrc` file and then .npmignore it.

**Comment by daffl** [comment]
If we have to we have to. I just moved them into package.json to not have a hundred dotfiles in the repo though :( Do you know why that is necessary?

**Comment by ekryski** [comment]
There are lots of issues around babel with react native. See https://github.com/facebook/react-native/issues/4548 for one example.

Basically the issue is the packager uses babel and because most of the plugins for babel are dev dependencies they are not included when installing modules and babel blows up.
